<?php

$form = $this->form;
$form->setAttribute('action', $this->url(
    'login/process',
    array(
        'action'     => 'authenticate',
    )
));



$form->prepare();

$form->get('submit')->setValue('Entrar');


echo $this->form()->openTag($form); ?>
<div class="form-group">
<?= $this->formRow($form->get('username')); ?>
</div>
<div class="form-group">
<?= $this->formRow($form->get('password')); ?>
</div>
<div class="form-group">
<?= $this->formSubmit($form->get('submit')); ?>
</div>
<?= $this->form()->closeTag();

if ($this->messages){
    echo '<ul>';
    foreach($this->messages as $message)
    {
       echo $message;
    }
    echo '</ul>';
}