 <script type="text/javascript">
	$(document).ready(function(){
		if($('select').val() == ''){
				$('.btn-default').hide();
			}
		$('select').click(function(){
			if($(this).val() == '')
			{
				$('.btn-default').hide();
			}else{
				$('.btn-default').show();
			}
		});
	});
</script>

<?php

$title = 'Escolher Jogador';
$this->headTitle($title);

$form->setAttribute('action', $this->url('user/play'));
$form->prepare();

echo $this->form()->openTag($form);	?>
<div class="form-group">
	<?= $this->formRow($form->get('jogadores'));?>
</div>
<div class="form-group">
	<?=	$this->formSubmit($form->get('submit'));?>
</div>
<?= $this->form()->closeTag(); ?>
<a href="<?php echo $this->url('user');?>"><button class="btn btn-warning">Voltar</button></a>
<?php

if ($this->messages){
    echo '<ul>';
    foreach($this->messages as $message)
    {
       echo $message;
    }
    echo '</ul>';
}